### ISSUE TITLE
unit tests update user cron tab

### ISSUE THREAD

**Issue by aheinz-fe** [vertexproject/synapse#121] opened 2017-01-19 13:59 UTC
After pulling master and running the unit tests, my crontab had a new entry:
```
@reboot "/Users/adam.heinz/Documents/GitHub/synapse/venv/bin/python3.5" -m synapse.tools.dmon --asboot &
```

**Comment by whippit** [comment] 2017-01-20 12:46
I'm currently unable to reproduce this behavior with checkout d76875a27d70b89d0a1ac5a6caffcc47f668160d (19 Jan 2017).  Are you able to reproduce this behavior?

**Comment by aheinz-fe** [comment] 2017-01-20 14:17
No, and the tests no longer run for me, exhausting file handles at some point. I'll just close this until synapse is supported on OSX.

**Comment by vertexmc** [comment] 2017-08-25 14:36
I can reproduce this. I noticed that I had a cronjob that seemed to try to run a bunch of temp files in dmon. these files were created during unit tests. It looks like it is not unit test specific though and is instead created upon using dmon.

https://github.com/vertexproject/synapse/blob/dfd4708423ddba4d34cd147e639971a1a84479ab/synapse/tools/dmon.py#L81

**Comment by vertexmc** [comment] 2017-08-25 14:56
Problem tests: https://github.com/vertexproject/synapse/blob/dfd4708423ddba4d34cd147e639971a1a84479ab/synapse/tests/test_dmon.py#L51-L70

**Comment by vertexmc** [comment] 2018-06-04 14:09
Closing issue as `cron` is removed

**Closed by vertexmc** 2018-06-04 14:09 UTC
Labels: bug
